dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
install:
- nvm install 6.9.2
- npm install -g typescript
script: bash src/main/scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - "$HOME/.m2"
after_deploy:
- bash src/main/scripts/npm-publish.bash $TRAVIS_TAG
